package cop.swt.widgets.enums;

public enum ColorRuleCheckTypeEnum
{
	START_CHECK_FROM_INIT,
	START_CHECK_FROM_FIRST_FOCUS_LOST,
	START_CHECK_FROM_FIRST_FOCUS_GAINED,
	START_CHECK_FROM_FIRST_KEY_PRESSED,
	CHECK_ONLY_IN_FOCUS
}
