package cop.swt.widgets.enums;

public enum DateTimePartEnum
{
	BACKGROUND_PART,
	COMPOSITE_PART,
	ENABLE_BUTTON_PART,
	CALENDAR_BUTTON_PART,
	SEPARATOR_PART,
	AMPM_PART,
	HOUR_PART,
	MINUTE_PART,
	SECOND_PART,
	YEAR_PART,
	MONTH_PART,
	DAY_PART
}
